AWSTemplateFormatVersion: 2010-09-09
Description: create VPC

Resources: 
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: machiyamaVPC
Outputs:
  myVPC:
    Value: !Ref myVPC
    Export: 
      Name: machiyamaVPC